services:
  bot:
    build: .
    environment:
      - IB_MONGO_URL=mongodb://db:27017
      - IB_CHART_SERVICE_URL=http://py-server:5301/bar
    env_file:
      - .env
  db:
    image: mongo
    ports:
      - "27017:27017"
  py-server:
    build:
      context: ./py-server
      dockerfile: Dockerfile
    ports:
      - "5301:5301"
