services:
  bot:
    build: .
    env_file:
      - .env
  db:
    image: mongo
    ports:
      - "27017:27017"
  py-server:
    build:
      context: ./py-server
      dockerfile: Dockerfile
    ports:
      - "5301:5301"
